# -*- coding: utf-8 -*-
"""FIzzBuzz.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nELnsl6XL4sF56OB5fC2VcoZTUbiU711
"""

for x in range(1, 100):

  if x % 3 == 0 and x % 5 == 0:

    print("fizzbuzz")

  elif x % 5 == 0:

    print("buzz")

  elif x % 3 == 0:

    print("fizz")

  else :print(x)



print(x)